#!url=https://raw.githubusercontent.com/60ve/rocketmodule/refs/heads/main/photomath/photomath.module

#!author=60ve

#!name=Photomath
#!desc=MITM script that fakes an active PhotoMath Genius subscription

#!icon=https://raw.githubusercontent.com/60ve/rocketmodule/refs/heads/main/icons/photomath.png

[Script]

Photomath=type=http-response,pattern=https://lapi.photomath.net/v4/me,requires-body=1,script-path=https://raw.githubusercontent.com/60ve/rocketmodule/refs/heads/main/photomath/photomath.js

[MITM]

hostname = %APPEND% lapi.photomath.net
