#!url=https://raw.githubusercontent.com/60ve/rocketmodule/refs/heads/main/spotify/spotufy.module

#!author=60ve
# 90% like not mine

#!name=Spotify
#!desc=MITM script that fakes an active Spotify Premium subscription

#!icon=https://raw.githubusercontent.com/60ve/rocketmodule/refs/heads/main/icons/spotify.png

[Header Rewrite]
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[MITM]
hostname = %APPEND% spclient.wg.spotify.com, *spclient.spotify.com

[Script]
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/60ve/rocketmodule/refs/heads/main/spotify/spotify-request-normalizer.js
spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/60ve/rocketmodule/refs/heads/main/spotify/spotify.js,script-update-interval=0
